### ISSUE TITLE
Write a timestream record using .Net AWSSDK NuGet packages

### ISSUE THREAD

**Issue by gabrielhruiz** [localstack-dotnet/localstack-dotnet-client#20]
## Expected Behavior
To write in LocalStack Timestream the records to see them in the web query editor.

## Actual Behavior
We use the code (which is shown in section "Anything else") to write records using .Net 6 and AWSSDK NuGet packages.

We are sure that the Timestream services are running and configured correctly in LocalStack. We can see this in the LoacalStack web and in the CLI using awslocal commands.

When we try to write several records at line 79 and throw the error: "Failed to discover the endpoint for the request. Requests will not succeed until an endpoint can be retrieved or an endpoint is manually specified." (complete stack trace is shown in section "Anything else" too). Then I try to Write a record using the CLI and that is written successfully.

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -dt -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY='API_KEY' localstack/localstack

#### Create DB

    awslocal timestream-write  create-database --database-name timeStreamDB

#### Create Table

    awslocal timestream-write  create-table --database-name timeStreamDB --table-name timeStreamTable

## Specifications

```markdown
- OS: Windows 11
- LocalStack: latest
- .Net 6
```

AWSSDK versions: 
```
<ItemGroup>
    <PackageReference Include="AWSSDK.TimestreamQuery" Version="3.7.2.78" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.13.12" />
    <PackageReference Include="AWSSDK.TimestreamWrite" Version="3.7.1.111" />
  </ItemGroup>
```

### StackTrace

Amazon.Runtime.Internal.EndpointDiscoveryResolverBase.ProcessInvokeEndpointOperation(String cacheKey, Func`1 InvokeEndpointOperation, Boolean endpointRequired)
   en Amazon.Runtime.Internal.EndpointDiscoveryResolverBase.ResolveEndpoints(EndpointOperationContextBase context, Func`1 InvokeEndpointOperation)
   en Amazon.TimestreamWrite.AmazonTimestreamWriteClient.EndpointOperation(EndpointOperationContextBase context)
   en Amazon.Runtime.Internal.EndpointDiscoveryHandler.DiscoverEndpoints(IRequestContext requestContext, Boolean evictCacheKey)
   en Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Energy.Cloud.Server.MeasurementsDTOHandler.<SaveRecords>d__6.MoveNext()
   en ...\MeasurementsDTOHandler.cs: línea 79

### .Net Code

```
using Amazon.TimestreamWrite;
using Amazon.TimestreamWrite.Model;
using CloudWatch;
using Energy.Cloud.Model;

namespace Energy.Cloud.Server
{
    public class MeasurementsDTOHandler
    {
        
        private readonly ICloudWatchLogs _logger;

        private readonly IAmazonTimestreamWrite _timeStreamClient;

        private readonly IConfiguration _configuration;


        public MeasurementsDTOHandler(ICloudWatchLogs logger, IAmazonTimestreamWrite timeStreamClient, IConfiguration configuration)
        {
            _logger = logger;

            _timeStreamClient = timeStreamClient;

            _configuration = configuration;
        }

        public async Task Process(House house, MeasurementsDTO measurements)
        {
            var records = CreateMessagesToTimeStream(house, measurements);
            await SaveRecords(records);
        }

        private List<Amazon.TimestreamWrite.Model.Record> CreateMessagesToTimeStream(House house, MeasurementsDTO measurements)
        {
            var records = new List<Amazon.TimestreamWrite.Model.Record>();

            foreach(var measurement in measurements.Measurements)
            {
                string timeString = ((DateTimeOffset)Convert.ToDateTime(measurement.TimeStamp)).ToUnixTimeSeconds().ToString();

                var dimensions = new List<Dimension>{
                     new Dimension { Name = "GrafanaUserName", Value = house.GrafanaUserName },
                     new Dimension { Name = "HouseId", Value = house.Id.ToString() },
                     new Dimension { Name = "Device", Value = measurement.DeviceUserName },

                };

                var record = new Amazon.TimestreamWrite.Model.Record
                {
                    Dimensions = dimensions,
                    MeasureName = measurement.MeasurementType.ToString(),
                    MeasureValue = ConvertValue(MeasureValueType.DOUBLE, measurement.Value.ToString()),
                    MeasureValueType = MeasureValueType.DOUBLE,
                    Time = timeString,
                    TimeUnit = TimeUnit.SECONDS,
                    
                };

                records.Add(record);
            }
           
            return records;

        }

        private async Task SaveRecords(List<Record> records)
        {
            foreach (var chunk in records.Chunk(100))
            {
                try
                {

                    var writeRecordsRequest = new WriteRecordsRequest
                    {
                        DatabaseName = _configuration.GetSection("TimeStream").GetSection("Database").Value,
                        TableName = _configuration.GetSection("TimeStream").GetSection("TableName").Value,
                        Records = chunk.ToList()
                    };
                    WriteRecordsResponse response = await _timeStreamClient.WriteRecordsAsync(writeRecordsRequest);
                                

                }
                catch (RejectedRecordsException e)
                {
                    _logger.Error("RejectedRecordsException:" + e.ToString());
                    
                    foreach (RejectedRecord rr in e.RejectedRecords)
                    {
                        _logger.Error("RecordIndex " + rr.RecordIndex + " : " + rr.Reason);
                    }

                }
                catch (Exception ex)
                {
                    _logger.Error(ex.ToString());
                }
            }

        }

        private string ConvertValue(Amazon.TimestreamWrite.MeasureValueType valueType, string measureValue)
        {
            if (valueType == Amazon.TimestreamWrite.MeasureValueType.DOUBLE)
            {
                return Convert.ToDouble(measureValue).ToString().Replace(",", ".");
            }

            return measureValue;
        }
    }
}

```

**Comment by Blind-Striker** [comment]
Hi @gabrielhruiz thanks for the detailed information. I'm going to check the issue but I'm not sure if it relates to LocalStack.Client or Localstack itself. Will inform you about progress

**Comment by Blind-Striker** [comment]
I am working on v1.4.0 (https://github.com/localstack-dotnet/localstack-dotnet-client/pull/22) and have updated several dependencies, including:

- AWSSDK.TimestreamWrite v3.7.100.62
- Localstack Image v1.3.1
- AWSSDK.Core v3.7.103

I attempted to reproduce the potential bug and was successful in adding a record to the database without encountering any exceptions. One of the dependency updates likely resolved the issue. I plan to release the new update today. I will be closing this issue.
