### ISSUE TITLE
Localstack.Client.Extensions awsoptions argument null exception 

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [localstack-dotnet/localstack-dotnet-client#35]
I recently tried upgrading the client.extensions package from 1.2.0 -> 1.2.1 and suddenly started getting argument null exceptions during dependency injection of the aws service when UseLocalStack is false. It looks like this exception was added in the latest release, but I cannot tell what the reasoning for this breaking change was. 

Our code does not make use of the `AWS` config section in our code and instead relies on the credential chain to either load local profiles or iam roles when deployed.  As such we do not pass in `AWSOptions` with calls to `AddAWSServiceLocalStack`

[diff link](https://github.com/localstack-dotnet/localstack-dotnet-client/compare/1.4.0...1.4.1#diff-b88d68718a1c9c1cffc37c5591ff1ee9af8af724171cb78462b8a67826ea0c6aR16-R20)

## Expected Behavior
The requested aws service should be returned if the aws options object is null.

## Actual Behavior
ArgumentNullException is thrown.

## Steps to Reproduce the Problem

  1. Use `AddServiceLocalStack<T>` without explicitly passing in AWSOptions
  1. ArgumentNullException should be throw when resolving T.

## Specifications

  - Version: Localstack.Client.Extensions 1.2.1

**Comment by Blind-Striker** [comment]
Hi @christopher-taormina-zocdoc ,

Thanks for the issue; I'll start investigating.

**Comment by Blind-Striker** [comment]
I found the issue and will publish a new release today. Thank you

**Comment by Blind-Striker** [comment]
Hey @christopher-taormina-zocdoc I have released the new version LocalStack.Client.Extentions;

https://www.nuget.org/packages/LocalStack.Client.Extensions/1.2.2

Could you confirm the bug is fixed when you have time?

**Comment by christopher-taormina-zocdoc** [comment]
@Blind-Striker Sorry for not responding earlier, but I pulled the latest version and everything looks good. Thanks for the help!
