### ISSUE TITLE
Unable to create API Gateway Rest API

### ISSUE THREAD

**Issue by ghost** [localstack-dotnet/localstack-dotnet-client#40]
## Expected Behavior
Creates API Gateway Rest API

## Actual Behavior
The manually configured client works but the Localstack.NET client won't
Throws AmazonAPIGatewayException
`No moto route for service apigateway on path /ttp://apigateway.us-east-1.amazonaws.com/restapis found`

## Steps to Reproduce the Problem

  - MRE: https://github.com/vengut/LocalstackTest/blob/master/Program.cs
     - Logs: https://github.com/vengut/LocalstackTest/actions/runs/11584711661/job/32252369266

## Specifications

  - Version: Localstack 3.7.1, LocalStack.Client 1.5.0
  - Platform: Linux (Seen it on Windows & Mac too)
  - Subsystem: Ubuntu

**Comment by Blind-Striker** [comment]
Hey Ghost,

I believe this might be a [similar known issue](https://github.com/localstack-dotnet/localstack-dotnet-client?tab=readme-ov-file#known-issues). I can open an issue in the LocalStack repo, but could you try running it with the latest version of the LocalStack container first? There's a chance this issue has been resolved in the latest version.

**Comment by vengut** [comment]
Nice tyty it worked with [latest](https://github.com/vengut/LocalstackTest/actions/runs/11595638147/job/32284723239) (but not with [3.8.1](https://github.com/vengut/LocalstackTest/actions/runs/11595606637/job/32284616398)) on Ubuntu.

**Comment by Blind-Striker** [comment]
Yes, by the time I submitted the issue, they had already published version 3.8.1. They fixed the issue afterward, and it’s likely that the fix will be included in version 3.8.3. The latest is their nightly builds AFAIK.
