### ISSUE TITLE
LocalStack breaking change: New service port

### ISSUE THREAD

**Issue by sahussaimc** [localstack-dotnet/localstack-dotnet-client#5]
## Expected Behavior
LocaStack dotnet client should connect with LocalStack.

## Actual Behavior
LocalStack dotnet client fails to connect with exception:
"No connection could be made because the target machine actively refused it."

## Details
A breaking change has been made in LocalStack from docker tag 0.11.5+ where services now only use a single edge port **4566**.
Relevant details can be found here:
https://github.com/localstack/localstack/issues/2983
https://github.com/localstack/localstack/pull/2905
https://github.com/localstack/localstack/issues/3072

**Comment by bravecobra** [comment]
've got the same issue here. Is there a way to set the defaults?

**Comment by sahussaimc** [comment]
@bravecobra If you're willing to create a local build of the library, you can find the details to set ports to 4566 in the code here:
https://github.com/localstack/localstack/issues/3072#issuecomment-703856718

It worked for me.

**Comment by Blind-Striker** [comment]
Will do the necessary changes as soon as possible.

**Comment by Blind-Striker** [comment]
@sahussaimc, @bravecobra new version [LocalStack.Net](https://github.com/localstack-dotnet/localstack-dotnet-client) has released. All service has point ports use 4566 by default, but it also backward compatible.

And we have released another package called [LocalStack.Client.Extensions](https://www.nuget.org/packages/LocalStack.Client.Extensions/) which allow you to use LocalStack.Client similar to [AWSSDK.Extensions.NETCore.Setup](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-netcore.html)

See [Readme](https://github.com/localstack-dotnet/localstack-dotnet-client#localstack-client-extensions) for the details.

**Comment by sahussaimc** [comment]
@Blind-Striker Thank you!
