### ISSUE TITLE
Request uprev support - AWSSDK.Core (>= 3.3.106.5 && < 3.4.0) 

### ISSUE THREAD

**Issue by dhagan-va** [localstack-dotnet/localstack-dotnet-client#6]
Request support for 3.5.xxx  - turns out this warning is bubbling up into our CDK templates when we include localstack unit tests.

## Actual Behavior

Detected package version outside of dependency constraint: LocalStack.Client 1.0.0 requires AWSSDK.Core (>= 3.3.106.5 && < 3.4.0) but version AWSSDK.Core 3.5.1.42 was resolved.

**Comment by Blind-Striker** [comment]
@dhagan-va new version [LocalStack.Net](https://github.com/localstack-dotnet/localstack-dotnet-client) has released. All service has point ports use 4566 by default, but it also backward compatible. And support added for AWSSDK.Core 3.5.0 and above

And we have released another package called [LocalStack.Client.Extensions](https://www.nuget.org/packages/LocalStack.Client.Extensions/) which allow you to use LocalStack.Client similar to [AWSSDK.Extensions.NETCore.Setup](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-netcore.html)

See [Readme](https://github.com/localstack-dotnet/localstack-dotnet-client#localstack-client-extensions) for the details.
