### ISSUE TITLE
Rename .AddAwsService()

### ISSUE THREAD

**Issue by kewur** [localstack-dotnet/localstack-dotnet-client#9]
Hi, I was wondering if we could rename .AddAwsService to .AddAWSServiceLocalStack or some other name. Currently, these two are extremely similar the AWS one being uppercase and the localstack one being PascalCase. They are very easy to mix up.

**Comment by Blind-Striker** [comment]
Hi, I have gotten similar similar suggestions from other people as well. I would use AddAWSService itself but using the same method name in extension methods for the same class prevented. I'll add the method name you suggested as an alternative in the next version.

**Comment by Blind-Striker** [comment]
Hi @kewur a new extension method called `AddAWSServiceLocalStack` added as you suggested. `AddAwsService` is still valid but alternatively, you can use  `AddAWSServiceLocalStack` now.

The new version has other new changes as well, see [v1.2.0](https://github.com/localstack-dotnet/localstack-dotnet-client/releases/tag/v1.2.0) release notes.

**Comment by kewur** [comment]
Thank you!
